function [SC, plottables]=state_colors_olf(obj)
% Colors that the various states take when plotting
SC = struct( ...
  'wait_for_cpoke',  'w',              ...  
  'wait_for_apoke',  [0.7 0.7 0.95],   ...  
  'left_reward',     [0.5 0.9 0.5],    ...
  'right_reward',    [0.5 0.9 0.5],    ...
  'hold_in_center',  [0.5 0.9 0.5],    ...
  'extra_iti',       [0.9 0 0]);



% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
  'wait_for_cpoke'     1:6   ; ...
  'wait_for_apoke'     1:6   ; ...
  'left_reward'        1:7   ; ...
  'right_reward'       1:7   ; ...
  'hold_in_center'     1:7   ; ...
  'extra_iti'          1:7   ; ...
             };

