function [SC, plottables]=state_colors(obj)

% Colors that the various states take when plotting
SC = struct( ...
  'wait_for_cpoke',    [1 0.75 0.75],   ...  
  'odor_poke_in',      [0 0.1 0.95],   ...
  'odor_valve_on',     [1 0.1 0.95],   ...
  'hold_cpoke',        [0.9 0.9 0.5],   ... 
  'wait_for_apoke',    [0.8 0.1 0.95],    ...
  'left_reward',       [0.5 0.9 0.5],    ...
  'right_reward',      [0.5 0.0 0.5],    ...
  'no_reward',         [0.3 0.3 0.3],    ...
  'drink_time',        [0.6 0.12 0.12],    ...
  'iti',               [0.7 0.7 0.7],    ...
  'extra_iti',         [0.5 0.5 0.5],    ...
  'dead_time',         'w',    ...
  'state35',           [0.3 0.3 0.3]);


% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
  'dead_time'          1:7   ; ...
  'wait_for_cpoke'     1:6   ; ...
  'odor_poke_in'       1:7   ; ...
  'odor_valve_on'      1:7   ; ...
  'hold_cpoke'         1:7   ; ...
  'wait_for_apoke'     1:6   ; ...
  'left_reward'        1:7   ; ...
  'right_reward'       1:7   ; ...
  'no_reward'          1:7   ; ...
  'drink_time'         1:7   ; ...
  'iti'                1:7   ; ...
  'extra_iti'          1:7   ; ...
             };
