function [SC, plottables]=state_colors(obj)
% Colors that the various states take when plotting
SC = struct( ...
  'wait_for_cpoke',  'w',              ...
  'odor_valve_on' ,   [0.9 0 0.4],        ...
  'hold_in_center',   [0.9 0 0.4],        ...
  'wait_for_apoke',  [0.5 0.5 0.5],   ...  
  'left_reward',     [0.3 0.9 0.3],    ...
  'right_reward',    [0.3 0.9 0.3],    ...
  'drink_time',      [0.3 0 0.9],    ...
  'extra_iti',       [0.9 0 0]);



% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
  'wait_for_cpoke'     1:7   ; ...
  'odor_valve_on'        1:7   ; ...
  'hold_in_center'     1:7   ; ...
  'wait_for_apoke'     1:7   ; ...
  'left_reward'        1:7   ; ...
  'right_reward'       1:7   ; ...
  'drink_time'         1:7   ; ...
  'extra_iti'          1:7   ; ...
             };

