function [SC, plottables]=state_colors(obj)

% Colors that the various states take when plotting
SC = struct( ...
  'wait_for_cpoke',  [.99 .55  .15],   ...  %  'odor_travel_time', [0 0.9 0.9],   ...
  'rand_valve_delay', [0.9 0.1 0.95],   ...
  'valid_samp_time', [0 0.9 0.9],   ... 
  'hold_cpoke',      [0 0.9 0.9],   ... 
  'wait_for_apoke',  [.99 .2 .6],    ...
  'left_reward',     [0.2 0.9 0.2],    ...
  'right_reward',    [0.2 0.9 0.2],    ...
  'drink_time',      [0.2 0.9 0.2],    ...
  'left_dirdel',     [0.2 0.9 0.2],    ...  
  'right_dirdel',    [0.2 0.9 0.2],    ...
  'timeout',         [0.6 0.12 0.12],  ...
  'ITI',             [0.99 0.99 0.6],    ...
  'state35',         [0.6 0.6 0.8]);
%  'extra_iti',       [0.9 0 0], ...
%  'hit_state',       [0.5 0.9 0.5]);


% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
%  'dead_time'          1:7   ; ...
  'wait_for_cpoke'     1:6   ; ... %  'odor_travel_time'   1:7  ; ...
  'rand_valve_delay'    1:7  ; ...
  'valid_samp_time'    1:7   ; ...
  'hold_cpoke'          1:7   ; ...
  'wait_for_apoke'     1:6   ; ...
  'left_reward'        1:7   ; ...
  'left_dirdel'        1:7   ; ...
  'right_dirdel'       1:7   ; ...
  'right_reward'       1:7   ; ...
  'drink_time'         1:7   ; ...
  'timeout'            1:7   ; ...
%  'extra_iti'          1:7   ; ...
  'ITI'                1:7   ; ...
%  'hit_state'          1:7   ; ...
             };

