function [SC, plottables]=state_colors(obj)

% Colors that the various states take when plotting

SC = struct( ...
  'wait_for_cpoke',  'w',              ...  
  'sound_playing',   [0.2 0.2 0.99],   ...  
  'wait_for_apoke',  [0.7 0.7 0.95],   ...  
  'left_reward',     [0.7 1 0.7],    ...
  'right_reward',    [0.7 1 0.7],    ...
  'iti',             [0.6 0.6 0.6],  ...
  'extra_iti',       [0.9 0 0]);


% Which states to plot, together with which event indices indicate an
% exit from that type of state
plottables = { ...
  'wait_for_cpoke'     1:6   ; ...
  'sound_playing'      1:7   ; ...
  'wait_for_apoke'     1:6   ; ...
  'left_reward'        1:7   ; ...
  'right_reward'       1:7   ; ...
  'extra_iti'          1:7   ; ...
  'iti'                1:7   ; ...
             };

