title: BControl Documentation
description: Behavioral Experimentation System Documentation
baseurl: "/ratter"
url: "https://limlabswc.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Permalinks - use simple structure
permalink: pretty

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - "_pages"

# Defaults - ensure all files use our layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
