markdown: kramdown
theme: minima
title: "BControl Documentation"
baseurl: ""
url: "https://bcontrol.lim.bio"

# Enable GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
