markdown: kramdown
theme: minima
title: "BControl Documentation"
baseurl: "/ratter"
url: "https://limlabswc.github.io"

# Enable GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
