source "https://rubygems.org"

# Use the GitHub Pages meta-gem to pin a compatible Jekyll/Plugins set
gem "github-pages", group: :jekyll_plugins

# Ruby 3.x no longer ships webrick by default
gem "webrick", "~> 1.8"
